---

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - python-pip

- name: docker apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: docker apt-repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: install docker-ce
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce

- name: install docker pip modules
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-cloud
    - docker-py

...
