---

- hosts: provisioners

  vars:
    do_ssh_keyname: "{{ lookup('env', 'PROVISIONER_DO_SSH_KEYNAME') }}"
    do_ssh_keyfile: "{{ lookup('env', 'PROVISIONER_DO_SSH_KEYFILE') }}"
    ssh_private_keyfile: "{{ lookup('env', 'PROVISIONER_SSH_PRIVATE_KEYFILE') }}"
    do_token: "{{ lookup('env', 'PROVISIONER_DO_TOKEN') }}"
    domain_base: "{{ lookup('env', 'PROVISIONER_DOMAIN_BASE') }}"
    droplets:
    - droplet-jenkins

  tasks:
  
  - name: install packages
    become: true
    become_user: root
    apt: name={{item}} state=installed
    with_items:
    - python-pip

  - name: install python packages
    pip: name={{item}} state=present
    with_items:
    - dopy

  - debug: var=do_ssh_keyname

  - name: check ssh keys
    digital_ocean:
      state: present
      command: ssh
      name: '{{ do_ssh_keyname }}'
      ssh_pub_key: "{{ lookup('file', do_ssh_keyfile) }}"
      api_token: "{{ do_token }}"
    register: do_ssh_key

  - name: create new droplet
    digital_ocean:
      state: present
      command: droplet
      name: "{{ item }}"
      unique_name: yes
      api_token: "{{ do_token }}"
      size_id: 2gb
      region_id: nyc3
      # "id": 18325354,
      # "name": "7.2 x64",
      # "distribution": "CentOS",
      image_id: 18325354
      wait_timeout: 500
      ssh_key_ids: "{{ do_ssh_key.ssh_key.id }}"
    with_items: '{{ droplets }}'
    register: droplet_inv

  - debug: msg="IP is {{ item.droplet.ip_address }}"
    with_items: '{{ droplet_inv.results }}'

  - name: add droplets to inventory
    add_host:
      name: "{{ item.droplet.ip_address }}"
      ansible_ssh_private_key_file: "{{ ssh_private_keyfile }}"
      ansible_ssh_user: root
      groups: ansibletest
    with_items: '{{ droplet_inv.results }}'

- hosts: ansibletest
  roles:
  - common
  - docker
  - jenkins
  - role: nginx
    domain_base: "{{ lookup('env', 'PROVISIONER_DOMAIN_BASE') }}"
    tags: ["http"]

...
