---

- hosts: localhost
  become: true
  become_user: root
    
  tasks:

  - name: install packages
    become: true
    become_user: root
    apt: name={{item}} state=installed
    with_items:
    - python-pip
    tags:
    - always

  - name: install python packages
    pip: name={{item}} state=present
    with_items:
    - dopy
    tags:
    - always

  roles:
  - weave-cloud
  - rsyslog
  - openvpn

...
