all:
  vars:
    ansible_ssh_private_key_file: /home/bwilson/.ssh/bwilson-home-2017-id_rsa
  hosts:
    work-linux:
      ansible_host: 192.168.1.115
      ansible_connection: local
    mini-monitor:
      ansible_host: 192.168.1.102
    mini-basement-media:
      ansible_host: 192.168.1.113
    i5-miniitx:
      ansible_host: 192.168.1.109

