---

- hosts: all
  become: true
  become_user: root

  tasks:

  - name: install pip
    easy_install:
      name: pip

  - name: install packages
    become: true
    become_user: root
    apt: name={{item}} state=installed
    with_items:
      - emacs24-nox
      - vim

  - name: install python packages
    pip: name={{item}} state=present
    with_items:
      - dopy
      - ansible-lint

  roles:
    - update
    - docker
    - prometheus-node-exporter
    - prometheus
    - grafana
    - ipfs
    - bwilson
    - kubeadm

...
