---

- name: download weave scope
  command: curl -L git.io/scope -o /usr/local/bin/scope creates=/usr/local/bin/scope

- name: make scope executable
  file:
    path: /usr/local/bin/scope
    mode: "0755"

...
