---

- name: create dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: bwilson
  with_items:
    - "{{ bwilson.home }}/.local/bin"

- name: install binaries
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip
    dest: "{{ bwilson.home }}/.local/bin/"
    remote_src: yes
    mode: 0755
    owner: bwilson
  with_items:
    - { url: "https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip",
        name: terraform
      }

...
