---

- name: install packages
  yum: name={{ item }} state=present
  with_items:
  - docker

- name: Restart docker
  service: name=docker enabled=yes state=started

- name: install pip
  command: easy_install pip

- name: install python packages
  pip: name=docker-py version=1.9.0 state=forcereinstall
