---

- name: create prometheus home
  file:
    path: "{{ prometheus_base }}"
    state: directory

- name: template config file
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_base }}/prometheus.yml"
  notify: prometheus_restart

- name: start prometheus container
  docker_container:
    name: prometheus
    image: "prom/prometheus:{{ prometheus.version }}"
    network_mode: host
    restart_policy: always
    volumes:
      - "{{ prometheus_base }}:/prometheus"
    command: >
      --config.file=/prometheus/prometheus.yml
      --storage.tsdb.path=/tmp/data
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles

...
